### ISSUE TITLE
Possibilité de faire un seul fichier .json

### ISSUE THREAD

**Issue by Eliwena** [Dainerx/mapper_i18n#4]
Au lieu d'avoir un fichier .json pour chaque fichier que tu possèdes, pourquoi ne pas mettre en lien un fichier qui regrouperais tous les éléments de translate de toutes les pages d'un projet, ou de les regrouper dans un dossier ?

**Comment by Dainerx** [comment]
Hey @Eliwena, I released v1.1 and implemented merging functionality.

Please go take a [look](https://github.com/Dainerx/mapper_i18n#usage), looking forward to your feedback
